# Generated by Django 2.2.6 on 2019-11-04 12:26

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name=user.models.Users)),
                ('mainphoto', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='UsersCategories',
            fields=[
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Users')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Categories', unique=True)),
            ],
            options={
                'db_table': 'userscategories',
            },
        ),
        migrations.CreateModel(
            name='GroupsCategories',
            fields=[
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='group.Groups')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Categories', unique=True)),
            ],
            options={
                'db_table': 'groupscategories',
            },
        ),
    ]
